- name: Replace CentOS mirrors with vault.centos.org
  become: yes
  replace:
    path: /etc/yum.repos.d/CentOS-Base.repo
    regexp: '^mirrorlist=.*$'
    replace: '# \g<0>'

- name: Set baseurl to vault.centos.org (base)
  become: yes
  blockinfile:
    path: /etc/yum.repos.d/CentOS-Base.repo
    block: |
      [base]
      name=CentOS-7 - Base
      baseurl=http://vault.centos.org/7.9.2009/os/$basearch/
      gpgcheck=1
      gpgkey=http://vault.centos.org/7.9.2009/os/$basearch/RPM-GPG-KEY-CentOS-7

      [updates]
      name=CentOS-7 - Updates
      baseurl=http://vault.centos.org/7.9.2009/updates/$basearch/
      gpgcheck=1
      gpgkey=http://vault.centos.org/7.9.2009/os/$basearch/RPM-GPG-KEY-CentOS-7

      [extras]
      name=CentOS-7 - Extras
      baseurl=http://vault.centos.org/7.9.2009/extras/$basearch/
      gpgcheck=1
      gpgkey=http://vault.centos.org/7.9.2009/os/$basearch/RPM-GPG-KEY-CentOS-7

#- name: Clean and refresh yum cache
#  become: yes
#  shell: |
#    yum clean all
#    yum makecache

- name: Install OpenJDK 11
  become: yes
  yum:
    name: java-11-openjdk-headless
    state: present
